const sdata = [
    {   id:1,
        imgsrc:"https://m.media-amazon.com/images/M/MV5BYTA2OGExMTctYTAxYS00NjM0LTljZjAtYjViZWRiMDdiMGRkXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_UY209_CR1,0,140,209_AL_.jpg",
        title:" netflix original show",
        sname:"Daredevil",
        link:"https://www.hotstar.com/",
    },
    {   id:2,
        imgsrc:"https://m.media-amazon.com/images/M/MV5BMTY0NzkxNDcxNF5BMl5BanBnXkFtZTgwOTI5ODM5MzI@._V1_UY209_CR0,0,140,209_AL_.jpg",
        title:" netflix original show",
        sname:"Godless",
        link:"https://www.netflix.com/watch/80097141?source=imdb",


    },
    {   id:3,
        imgsrc:"https://m.media-amazon.com/images/M/MV5BYzgwMWI4ZGMtOGYyMi00ZmYyLWE0MzUtYmU5MjE1NDQ5MDhmXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_UY209_CR0,0,140,209_AL_.jpg",
        title:" netflix original show",
        sname:"Love",
        link:"https://www.netflix.com/watch/80026506?source=imdb",
    },
    {   id:4,
        imgsrc:"https://m.media-amazon.com/images/M/MV5BMTgyNTQyNjUwN15BMl5BanBnXkFtZTgwNjMwNjUzNzM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        title:" netflix original show",
        sname:"Unbreakable ",
        link:"https://www.netflix.com/watch/80025384?source=imdb",
    },
    {   id:5,
        imgsrc:"https://m.media-amazon.com/images/M/MV5BOTE0MjQ1NDU3OV5BMl5BanBnXkFtZTgwNTI4MTgwNzM@._V1_UY209_CR0,0,140,209_AL_.jpg",
        title:" netflix original show",
        sname:" Sex education  ",
        link:"https://www.netflix.com/watch/80197526?source=imdb",
    }
]
export default sdata;